name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Initialize or Pull Amplify Project
        run: |
          npm install -g @aws-amplify/cli@latest
          amplify configure --usage-data-off
          # Check if Amplify project is already initialized, and if not, initialize it
          if [ ! -d "amplify" ]; then
            amplify init
          else
            amplify pull <app-id> # Replace <app-id> with your Amplify app ID
          fi
          
      - name: Deploy to Amplify
        run: amplify publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
